name: jaguar_mux_techempower_benchmark
version: 0.0.1
description: Techempower benchmark implementation for jaguar_mux

authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: http://jaguar-dart.github.io

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  jaguar:
  jaguar_mux: '>=0.0.3 <0.1.0'
  jaguar_query: '>=0.0.5 <0.1.0'
  jaguar_serializer:
  jaguar_mustache:
  jaguar_postgresql:
  jaguar_query_postgresql:

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
